RFIDTrackingWebApplication/Models/ActionEvent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RFIDTrackingWebApplication.Models
{

    public class ActionEvent
    {
        public int ActionId { get; set; }

        public double Temperature { get; set; }

        public DateTime Datetime { get; set; }

        public Int64 RfidNo { get; set; }

        public long AntennaIdfromReader { get; set; }

        public String ReaderId { get; set; }

        public String Location { get; set; }

        public bool Direction { get; set; }

        public virtual Person Person { get; set; }

        public virtual Antenna Antenna { get; set; }


    }
}

RFIDTrackingWebApplication/Controllers/ActionEventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Newtonsoft.Json;
using RFIDTrackingWebApplication.Models;

namespace RFIDTrackingWebApplication.Controllers
{
    public class ActionEventController : Controller
    {

        public readonly string url = "https://localhost:44378/api/";

        // GET: ActionEvent             
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            EventIndex eventModel = new EventIndex();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(url + "ActionEvents"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    eventModel.PersonEventsList = JsonConvert.DeserializeObject<List<ActionEvent>>(apiResponse);
                }
            }
            eventModel.PersonEventsWarningList = eventModel.PersonEventsList.Where(i => i.Temperature > 38);

            
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(url + "GetLocations"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    eventModel.Locations = JsonConvert.DeserializeObject<List<String>>(apiResponse);
                }
            }
            if (eventModel.Locations == null)
            {
                eventModel.Locations = new List<string>();
                string[] lokasyonlar = { "Bahçe", "Kadınlar Tuvaleti", "Erkekler Tuvaleti", "Mutfak", "Öğretmenler Odası", "1A", "2C", "3A", "3B" };
                eventModel.Locations.Add("Bahçe");
                eventModel.Locations.Add("Kadınlar Tuvaleti");
                eventModel.Locations.Add("Erkekler Tuvaleti");
                eventModel.Locations.Add("Mutfak");
                eventModel.Locations.Add("Öğretmenler Odası");
                eventModel.Locations.Add("1A");
                eventModel.Locations.Add("2C");
                eventModel.Locations.Add("3A");
                eventModel.Locations.Add("3B");
            }
            //return PartialView(LocationEvents);
            return View(eventModel);
        }


        // GET: People
        [HttpGet]
        public async Task<IActionResult> GetPeopleAtThisLocations(string location)
        {
            List<Person> peopleList;
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(url + "GetLocationEvents/" + location))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    peopleList = JsonConvert.DeserializeObject<List<Person>>(apiResponse);
                }
            }
            if (peopleList == null)
            {
                peopleList = new List<Person>();
            }
            peopleList.Add(new Person { RecordNo = 123456789, RfidNo = 4656262 ,Size ="S"});
            peopleList.Add(new Person { RecordNo = 234567895, RfidNo = 2515415, Size = "XS" });
            peopleList.Add(new Person { RecordNo = 382541254, RfidNo = 2596965, Size = "XL" });
            peopleList.Add(new Person { RecordNo = 486631458, RfidNo = 1696414, Size = "L" });
            peopleList.Add(new Person { RecordNo = 195212556, RfidNo = 4965965, Size = "M" });
            peopleList.Add(new Person { RecordNo = 567656856, RfidNo = 2596598, Size = "M" });
            peopleList.Add(new Person { RecordNo = 596526265, RfidNo = 6259659, Size = "M" });
            peopleList.Add(new Person { RecordNo = 959596662, RfidNo = 6594488, Size = "M" });
            peopleList.Add(new Person { RecordNo = 826262626, RfidNo = 1484896, Size ="XXL" });
            peopleList.Add(new Person { RecordNo = 264945965, RfidNo = 6259898, Size = "M" });
            peopleList.Add(new Person { RecordNo = 625699659, RfidNo = 9662598, Size = "XXS" });
            peopleList.Add(new Person { RecordNo = 625989595, RfidNo = 5148486, Size = "M" });

            ViewBag.lokasyon = location;

            return View(peopleList);
        }




        [HttpGet]
        public JsonResult GetRow()
        {
            Random rastgele = new Random();
            int rfid = rastgele.Next(10000000, 900000000);
            bool direct = rastgele.Next(0, 2) > 0;
            double temperature = rastgele.Next(340, 390);
            string[] lokasyonlar = { "Bahçe", "Kadınlar Tuvaleti", "Erkekler Tuvaleti", "Mutfak", "Öğretmenler Odası", "1A", "2C", "3A", "3B" };
            int lcno = rastgele.Next(0, lokasyonlar.Length);

            ActionEvent actionEventList = new ActionEvent
            {
                Datetime = DateTime.Now,
                Person = new Person
                {
                    RfidNo = rfid
                },
                Temperature = temperature / 10,
                Antenna = new Antenna
                {
                    Location = lokasyonlar[lcno],
                    Direction = direct
                }
            };

            return Json(actionEventList);
        }
        public static int PreviousId=0;
        // GET: ActionEvent             
        [HttpGet]
        public async Task<IActionResult> getData()
        {
            string apiResponse;
            List<ActionEvent> PersonEventsList = new List<ActionEvent>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(url + "ActionEvents"))
                {
                    apiResponse = await response.Content.ReadAsStringAsync();
                    PersonEventsList = JsonConvert.DeserializeObject<List<ActionEvent>>(apiResponse);
                }
                ActionEvent lastActionEvent = PersonEventsList.LastOrDefault();
                if (lastActionEvent == null || lastActionEvent.ActionId == PreviousId)
                {
                    return Json(null);
                }
                else
                {
                    PreviousId = lastActionEvent.ActionId;
                    return Json(lastActionEvent);
                }
                
            }
        }
    }
}

RFIDTrackingWebApplication/Views/ActionEvent/GetPeopleAtThisLocations.cshtml
@model IEnumerable<RFIDTrackingWebApplication.Models.Person>

@{
    ViewData["Title"] = "GetPeopleAtThisLocations";
}

    <h1>@ViewBag.lokasyon Konumunda Bulunan Kişiler</h1>

<table class="table">
    <thead>
        <tr>
            <th>Sicil No</th>
            <th>RFID No</th>
            <th>Beden</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RecordNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RfidNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Size)
            </td>
        </tr>
}
    </tbody>
</table>

RFIDTrackingWebApplication/Views/ActionEvent/Index.cshtml
@model EventIndex

@{
    ViewData["Title"] = "Index";
}


<div class="container-fluid p-3 mb-2 text-white bg-dark">
    <div class="container-fluid  row">
        @*<div class="col-2"> <img src="../Assets/AkarLogo.png" class="rounded" alt="Cinque Terre"></div>*@
        <div class="col-6">
            <h2>Çalışan Takip Sistemi</h2>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-9">
            <div class="container-fluid row" style="text-align:center;">
                <h3>Kayıt Listesi</h3>
            </div>
            <div class="container-fluid row">
                <div style="height: 400px; overflow: scroll;  border: 5px black;" class="container text-white bg-dark">
                    <table id="EventListTable" class="table table-dark table-sm table-striped table-bordered m-2">
                        <thead>
                            <tr>
                                <th>Zaman</th>
                                <th>Tarih</th>
                                <th>Etiket No</th>
                                <th>Vücut Sıcaklığı</th>
                                <th>Konum</th>
                                <th>Yön</th>
                            </tr>
                        </thead>
                        <tbody style="height: 400px !important; overflow: scroll; ">
            @foreach (var r in Model.PersonEventsList)
            {
                <tr>
                    <td>@r.Datetime</td>
                    <td>@r.Datetime</td>
                    <td>@r.RfidNo</td>
                    <td>@r.Temperature</td>
                    <td>@r.Location</td>
                    <td>@r.Direction</td>
                </tr>
            }
        </tbody>
                    </table>
                    </div>
                </div>
            </div>
            <div class="col-3">
                <div class="container-fluid row" style="text-align:center;">
                    <h3>Konumlar</h3>
                </div>
                <div class="container-fluid row">
                    <div style="height: 400px; overflow: scroll;  border: 5px black;" class="container text-white bg-dark">
                        <table id="Locations" class="table table-dark table-sm table-striped table-bordered m-2">
                            <tbody style="height: 400px !important; overflow: scroll; ">
                                <table id="LocationEvents" class="table table-dark table-sm table-striped table-bordered m-2">
                                    @foreach (var r in Model.Locations)
                                    {
                                        <tr>
                                            <td><button class="btnLocation" data-prop="@r">@r</button></td>
                                        </tr>
                                    }
                                </table>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="container-fluid">
        <div class="row">
            <div class="col-8">
                <div class="container-fluid row" style="text-align:center;">
                    <h3> Vücut Isısı Yüksek Olan Kayıtlar</h3>
                </div>
                <div class="container-fluid row">
                    <div style="height: 400px; overflow: scroll;  border: 5px black;" class="container text-white bg-dark">
                        <table id="EventListWarningTable" class="table table-dark table-sm table-striped table-bordered m-2">
                            <thead>
                                <tr>
                                    <th>Zaman</th>
                                    <th>Tarih</th>
                                    <th>Etiket No</th>
                                    <th>Vücut Sıcaklığı</th>
                                    <th>Konum</th>
                                    <th>Yön</th>
                                </tr>
                            </thead>
                            <tbody style="height: 400px !important; overflow: scroll; ">
                                @foreach (var r in Model.PersonEventsWarningList)
                                {
                                <tr>
                                    <td>@r.Datetime</td>
                                    <td>@r.Datetime</td>
                                    <td>@r.RfidNo</td>
                                    <td>@r.Temperature</td>
                                    <td>@r.Location</td>
                                    <td>@r.Direction</td>
                                </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-4">
                <div class="container-fluid row" style="text-align:center;">
                    <h3>Çalışmayan Okuyucular</h3>
                </div>
                <div class="container-fluid row">
                    <div style="height: 400px; overflow: scroll;  border: 5px black;" class="container text-white bg-dark">
                        <table id="Locations" class="table table-dark table-sm table-striped table-bordered m-2">
                            <tbody style="height: 400px !important; overflow: scroll; ">
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript">
        /*
            function getData() {
                $.ajax({
                    url: '/ActionEvent/Index',
                    success: function (html) {
                        $('#EventListTable').html(html);
                    }

                });
            }
            $(document).ready(function () {
                setInterval('getData();', 10);
            });
            */

        /*
        //////////////////////////////////////////////////////////////////////////
         function getdata() {
            $.getJSON("/ActionEvent/Index"), function (data) {

                $.each(data, function (i, item) {
                    var row = {
                        i.Datetime, item.Datetime, item.RfidNo, item.Temperature, item.Location, item.Direction
                    };
                    $(#EventListTable).tableInsertRows(row);
                });

                setInterval(getdata, 5000);

            });
        }
        ////////////////////////////////////////////////////////////////////////////////////////////7
        setInterval(getdata, 5000);
       
        //var table = $('#EventListTable').DataTable();

        $(#EventListTable).ajax.reload(function (json) {
            $("/ActionEvent/Index").val(json.lastInput);
        });
        
        ///////////////////////////////////////////////////////////////////////////////////7

        var table = $("/ActionEvent/Index").DataTable({
            ajax: "data.json"
        });

        setInterval(function () {
            table.ajax.reload();
        }, 1000);*/
        /*
        */

        $(function () {
            //debugger;
            setInterval(addRow, 1000);
            //addRow();
        });

        function addRow() {
            var rowsStyle = "";
            $.ajax({
                type: "GET",
                url: "/ActionEvent/getData",
                success: function (response) {
                    if (response.temperature >= 38) {
                        rowsStyle = "p-3 mb-2 bg-danger text-white";
                    }


                    var stringyön = "";
                    if (response.direction)
                        stringyön = "Giriş";
                    else
                        stringyön = "Çıkış";



                    var date = new Date(Date.parse(response.datetime));
                    //var resdate = response.date.parse;
                    var resdate = date.getFullYear() + "/" + (date.getMonth() + 1) + "/" + (date.getUTCDate());
                    var restime = date.getHours() + ":" + date.getMinutes();



                    row = ` <tr class="` + rowsStyle + `">
                                <td>`+ restime + `</td>
                                <td>`+ resdate + `</td>
                                <td>`+ response.rfidNo + `</td>
                                <td>`+ response.temperature + `</td>
                                <td>`+ response.location + `</td>
                                <td>`+ stringyön + `</td></tr>`;

                    $("#EventListTable tr:first").after(row);

                    var table = document.getElementById("EventListTable");
                    var rowCount = table.rows.length;

                    if (rowCount == 20) {
                        table.deleteRow(rowCount - 1);
                    }
                    ////////////////////////////////////////
                    if (response.temperature >= 38) {
                        var stringyön = "";
                        if (response.direction)
                            stringyön = "Giriş";
                        else
                            stringyön = "Çıkış";



                        var date = new Date(Date.parse(response.datetime));
                        //var resdate = response.date.parse;
                        var resdate = date.getFullYear() + "/" + (date.getMonth() + 1) + "/" + (date.getUTCDate());
                        var restime = date.getHours() + ":" + date.getMinutes();



                        row = `
                                <tr class="` + rowsStyle + `">
                                    <td>`+ restime + `</td>
                                    <td>`+ resdate + `</td>
                                    <td>`+ response.person.rfidNo + `</td>
                                    <td>`+ response.temperature + `</td>
                                    <td>`+ response.location + `</td>
                                    <td>`+ stringyön + `</td>
                                </tr>`;

                        $("#EventListWarningTable tr:first").after(row);

                        var table = document.getElementById("EventListWarningTable");
                        var rowCount = table.rows.length;

                        if (rowCount == 20) {
                            table.deleteRow(rowCount - 1);
                        }
                    }
                },
                failure: function (response) {
                    alert(response.responseText);
                },
                error: function (response) {
                    alert(response.responseText);
                }
            });
        }
        
        function deleterow(tableID) {
            var table = document.getElementById(tableID);
            var rowCount = table.rows.length;

            table.deleteRow(rowCount - 1);
        }
        
        



        $('.btnLocation').click(function () {
            var locationName = $(this).attr('data-prop');
            var data = JSON.stringify({ location: locationName });
            document.location.href = '@Url.Action("GetPeopleAtThisLocations", "ActionEvent")' + "?location=" + locationName;
            @*$.ajax({
                url: "/ActionEvent/GetPeopleAtThisLocations/" + locationName,
                    type: 'GET',
                    contentType: 'application/json; charset=utf-8',
                    dataType: "json",
                    success: function (data) {
                        window.location.href = '@Url.Action("GetPeopleAtThisLocations", "ActionEvent")';}
                   });*@
        });

    </script>